# Puerto de la aplicación
server.port=8080

# Conexión a Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://<HOST_O_IP_BD>:5432/<NOMBRE_BD>
spring.datasource.username=<USUARIO_BD>
spring.datasource.password=<PASSWORD_BD>
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Validación de JWT con AWS Cognito
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.<REGION>.amazonaws.com/<USER_POOL_ID>