server.port=8080

# SQLite guardará la base de datos en un archivo llamado pedidos360.db dentro de tu proyecto
spring.datasource.url=jdbc:sqlite:pedidos360.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate para SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Cognito
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_dzuH5paum